version: '2'

services:
  web:
    image: jekyll/jekyll:pages
    command: jekyll serve --watch --incremental
    container_name: jekyll
    ports:
      - '4000:4000'
    volumes:
      - ./:/srv/jekyll